// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDILbhYBNzwYOmfwms8l1njGLE-fW5lUc',
    appId: '1:932342565352:web:ffc96cc81f30dc860e3c5d',
    messagingSenderId: '932342565352',
    projectId: 'kilele-health',
    authDomain: 'kilele-health.firebaseapp.com',
    storageBucket: 'kilele-health.appspot.com',
    measurementId: 'G-9RYJVFR45F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7mI7VXsUec8EuGQxVdiEdx5YuH8kXLno',
    appId: '1:932342565352:android:07480bd0d9d55aba0e3c5d',
    messagingSenderId: '932342565352',
    projectId: 'kilele-health',
    storageBucket: 'kilele-health.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB68oOzzBkiHr34-1tpbi8ojpvt-xAzxYY',
    appId: '1:932342565352:ios:3a9eab5a4fd21cb90e3c5d',
    messagingSenderId: '932342565352',
    projectId: 'kilele-health',
    storageBucket: 'kilele-health.appspot.com',
    iosBundleId: 'org.kilele.kileleHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB68oOzzBkiHr34-1tpbi8ojpvt-xAzxYY',
    appId: '1:932342565352:ios:2b5f337195a39d8b0e3c5d',
    messagingSenderId: '932342565352',
    projectId: 'kilele-health',
    storageBucket: 'kilele-health.appspot.com',
    iosBundleId: 'org.kilele.kileleHealth.RunnerTests',
  );
}
